---
abstract: 'faster C<cpan-outdated> using a little more resources'
author:
  - KPEE.
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-cpanoutdated-coro
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  App::cpanoutdated::coro:
    file: lib/App/cpanoutdated/coro.pm
    version: '0.02'
requires:
  CPAN::DistnameInfo: '0.1'
  Coro: '0'
  File::Find::Rule: '0.20'
  IO::Zlib: '0'
  LWP: '0'
  Module::CoreList: '0'
  Module::Metadata: '1.000007'
  local::lib: '1.006008'
  perl: '5.008001'
  version: '0'
version: '0.02'
x_authority: cpan:KPEE
x_contributors:
  - 'KPEE <kpee.cpan@gmail.com>'
